version: '3.8'

services:
  postgres-db:
    image: postgres:16
    container_name: events_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: