spring.application.name=events-api
spring.datasource.url=jdbc:postgresql://localhost:5432/eventosbymc
spring.datasource.username=gabriel
spring.datasource.password=password
aws.region=us-east-1
aws.bucket.name=eventsbymc